<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\Container38bbmwx\appProdProjectContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/Container38bbmwx/appProdProjectContainer.php') {
    touch(__DIR__.'/Container38bbmwx.legacy');

    return;
}

if (!\class_exists(appProdProjectContainer::class, false)) {
    \class_alias(\Container38bbmwx\appProdProjectContainer::class, appProdProjectContainer::class, false);
}

return new \Container38bbmwx\appProdProjectContainer([
    'container.build_hash' => '38bbmwx',
    'container.build_id' => '10f917d3',
    'container.build_time' => 1656133394,
], __DIR__.\DIRECTORY_SEPARATOR.'Container38bbmwx');
